"""cleanup_redundant_tables_and_fix_cascades

Revision ID: f52949bac1f6
Revises: 5cbae36f3596
Create Date: 2026-05-10 05:59:13.946292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f52949bac1f6'
down_revision: Union[str, None] = '5cbae36f3596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_control_mappings')
    op.drop_table('user_question_assignments')
    op.drop_index(op.f('idx_permissions_role'), table_name='permissions')
    op.drop_index(op.f('idx_premetions_permission'), table_name='permissions')
    op.drop_index(op.f('idx_premetions_role'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('department_control_mappings')
    op.drop_index(op.f('idx_user_perms_perm'), table_name='user_premetions')
    op.drop_index(op.f('idx_user_perms_user'), table_name='user_premetions')
    op.drop_index(op.f('idx_user_premetions_permission'), table_name='user_premetions')
    op.drop_index(op.f('idx_user_premetions_user_id'), table_name='user_premetions')
    op.drop_table('user_premetions')
    op.drop_index(op.f('ai_questions_framework_id_idx'), table_name='ai_questions')
    op.drop_constraint(op.f('fk_ai_questions_framework'), 'ai_questions', type_='foreignkey')
    op.drop_constraint(op.f('ai_questions_control_id_fkey'), 'ai_questions', type_='foreignkey')
    op.drop_column('ai_questions', 'framework')
    op.drop_column('ai_questions', 'department')
    op.drop_column('ai_questions', 'position')
    op.drop_column('ai_questions', 'framework_id')
    op.drop_constraint(op.f('assessment_answers_session_id_fkey'), 'assessment_answers', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_answers', 'assessment_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assessment_sessions_user_id_fkey'), 'assessment_sessions', type_='foreignkey')
    op.drop_constraint(op.f('assessment_sessions_assessment_id_fkey'), 'assessment_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assessment_sessions', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assessments_organization_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('assessments_framework_id_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assessments', 'frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_assets_org'), table_name='assets')
    op.drop_constraint(op.f('assets_owner_id_fkey'), 'assets', type_='foreignkey')
    op.drop_constraint(op.f('assets_organization_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('control_positions_control_id_fkey'), 'control_positions', type_='foreignkey')
    op.drop_constraint(op.f('control_positions_position_id_fkey'), 'control_positions', type_='foreignkey')
    op.create_foreign_key(None, 'control_positions', 'framework_controls', ['control_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'control_positions', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_depts_org'), table_name='departments')
    op.drop_constraint(op.f('departments_organization_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_chunks_doc'), table_name='document_chunks')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_docs_org'), table_name='documents')
    op.drop_constraint(op.f('documents_organization_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('framework_controls_framework_id_fkey'), 'framework_controls', type_='foreignkey')
    op.create_foreign_key(None, 'framework_controls', 'frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_positions_dept'), table_name='positions')
    op.drop_constraint(op.f('positions_department_id_fkey'), 'positions', type_='foreignkey')
    op.create_foreign_key(None, 'positions', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('risks_asset_id_fkey'), 'risks', type_='foreignkey')
    op.create_foreign_key(None, 'risks', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_users_active'), table_name='users')
    op.drop_index(op.f('idx_users_org'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_position_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_position_id_fkey'), 'users', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_org'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False)
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.create_foreign_key(op.f('risks_asset_id_fkey'), 'risks', 'assets', ['asset_id'], ['id'])
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_foreign_key(op.f('positions_department_id_fkey'), 'positions', 'departments', ['department_id'], ['id'])
    op.create_index(op.f('idx_positions_dept'), 'positions', ['department_id'], unique=False)
    op.drop_constraint(None, 'framework_controls', type_='foreignkey')
    op.create_foreign_key(op.f('framework_controls_framework_id_fkey'), 'framework_controls', 'frameworks', ['framework_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_organization_id_fkey'), 'documents', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('idx_docs_org'), 'documents', ['organization_id'], unique=False)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    op.create_index(op.f('idx_chunks_doc'), 'document_chunks', ['document_id'], unique=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_organization_id_fkey'), 'departments', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('idx_depts_org'), 'departments', ['organization_id'], unique=False)
    op.drop_constraint(None, 'control_positions', type_='foreignkey')
    op.drop_constraint(None, 'control_positions', type_='foreignkey')
    op.create_foreign_key(op.f('control_positions_position_id_fkey'), 'control_positions', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('control_positions_control_id_fkey'), 'control_positions', 'framework_controls', ['control_id'], ['id'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_organization_id_fkey'), 'assets', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('assets_owner_id_fkey'), 'assets', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('idx_assets_org'), 'assets', ['organization_id'], unique=False)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_framework_id_fkey'), 'assessments', 'frameworks', ['framework_id'], ['id'])
    op.create_foreign_key(op.f('assessments_organization_id_fkey'), 'assessments', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'assessment_sessions', type_='foreignkey')
    op.drop_constraint(None, 'assessment_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_sessions_assessment_id_fkey'), 'assessment_sessions', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(op.f('assessment_sessions_user_id_fkey'), 'assessment_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'assessment_answers', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_answers_session_id_fkey'), 'assessment_answers', 'assessment_sessions', ['session_id'], ['id'])
    op.add_column('ai_questions', sa.Column('framework_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ai_questions', sa.Column('position', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_questions', sa.Column('department', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_questions', sa.Column('framework', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ai_questions_control_id_fkey'), 'ai_questions', 'framework_controls', ['control_id'], ['id'])
    op.create_foreign_key(op.f('fk_ai_questions_framework'), 'ai_questions', 'frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ai_questions_framework_id_idx'), 'ai_questions', ['framework_id'], unique=False)
    op.create_table('user_premetions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_premetions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_premetions_pkey')),
    sa.UniqueConstraint('user_id', 'permission', name=op.f('user_premetions_user_id_permission_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_premetions_user_id'), 'user_premetions', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_premetions_permission'), 'user_premetions', ['permission'], unique=False)
    op.create_index(op.f('idx_user_perms_user'), 'user_premetions', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_perms_perm'), 'user_premetions', ['permission'], unique=False)
    op.create_table('department_control_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('department_control_mappings_pkey')),
    sa.UniqueConstraint('department_id', 'control_id', name=op.f('department_control_mappings_department_id_control_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('premetions_pkey')),
    sa.UniqueConstraint('role', 'permission', name=op.f('premetions_role_permission_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_premetions_role'), 'permissions', ['role'], unique=False)
    op.create_index(op.f('idx_premetions_permission'), 'permissions', ['permission'], unique=False)
    op.create_index(op.f('idx_permissions_role'), 'permissions', ['role'], unique=False)
    op.create_table('user_question_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_question_assignments_pkey')),
    sa.UniqueConstraint('user_id', 'question_id', name=op.f('user_question_assignments_user_id_question_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('position_control_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('position_control_mappings_pkey')),
    sa.UniqueConstraint('position_id', 'control_id', name=op.f('position_control_mappings_position_id_control_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
